apiVersion: 1

datasources:
  - name: PathogenPortal-DB
    type: postgres
    access: proxy
    url: postgres:5432
    database: pathogens
    user: portal
    secureJsonData:
      password: portal_dev
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
